---
apiVersion: v1
kind: Service
metadata:
  name: gbedu-api
  namespace: gbedu-prod
  labels:
    app: gbedu-api
    app.kubernetes.io/name: gbedu-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: gbedu
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: gbedu-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
