"""
gbedu_core — shared foundation for all Gbẹdu services.

Import surface is intentionally flat so service code never needs
to know internal sub-module layout.
"""

from gbedu_core._uuid7 import uuid7str
from gbedu_core.config import (
	CelerySettings,
	DatabaseSettings,
	EmailSettings,
	JWTSettings,
	MLSettings,
	ObservabilitySettings,
	PaystackSettings,
	RedisSettings,
	Settings,
	StorageSettings,
	StripeSettings,
	get_settings,
)
from gbedu_core.db import (
	Base,
	SoftDeleteMixin,
	TimestampMixin,
	get_db,
	get_engine,
	init_db,
	make_session_factory,
	ping_database,
)
from gbedu_core.errors import (
	EC_AUTHENTICATION,
	EC_AUTHORIZATION,
	EC_CONFLICT,
	EC_DATABASE,
	EC_DATABASE_CONNECTION,
	EC_DATABASE_INTEGRITY,
	EC_GENERATION,
	EC_GENERATION_QUOTA,
	EC_INVALID_CREDENTIALS,
	EC_ML_SERVICE,
	EC_ML_TIMEOUT,
	EC_NOT_FOUND,
	EC_PAYMENT,
	EC_PAYMENT_DECLINED,
	EC_PAYMENT_WEBHOOK,
	EC_RATE_LIMIT,
	EC_STORAGE,
	EC_STORAGE_DELETE,
	EC_STORAGE_UPLOAD,
	EC_TOKEN_EXPIRED,
	EC_TOKEN_INVALID,
	# Error codes
	EC_VALIDATION,
	EC_WORKER,
	EC_WORKER_TIMEOUT,
	AuthenticationError,
	AuthorizationError,
	ConflictError,
	DatabaseConnectionError,
	DatabaseError,
	DatabaseIntegrityError,
	# Base
	GbeduError,
	GenerationError,
	GenerationQuotaError,
	InvalidCredentialsError,
	MLServiceError,
	MLServiceTimeoutError,
	NotFoundError,
	PaymentDeclinedError,
	PaymentError,
	PaymentWebhookError,
	RateLimitError,
	StorageDeleteError,
	StorageError,
	StorageUploadError,
	TokenExpiredError,
	TokenInvalidError,
	# Exception classes
	ValidationError,
	WorkerError,
	WorkerTimeoutError,
)
from gbedu_core.health import (
	AggregateHealth,
	HealthState,
	HealthStatus,
	check_database,
	check_ml_service,
	check_redis,
	check_storage,
)
from gbedu_core.logging import (
	LogContext,
	configure_logging,
	get_logger,
)
from gbedu_core.models import (
	BeatListing,
	BeatPurchase,
	GenerationJob,
	Invoice,
	InvoiceStatus,
	JobStatus,
	Language,
	ListingStatus,
	Payment,
	PaymentProvider,
	PaymentStatus,
	SubGenre,
	Subscription,
	SubscriptionStatus,
	SubscriptionTier,
	Track,
	TrackStatus,
	User,
	VoiceArchetype,
	VoiceModel,
	VoiceModelStatus,
)
from gbedu_core.schemas import (
	BeatListingRead,
	BeatPurchaseRead,
	GenerationRequest,
	GenerationResponse,
	InvoiceRead,
	JobRead,
	JobStatusUpdate,
	PaymentRead,
	RefreshRequest,
	SubscriptionRead,
	TokenResponse,
	TrackCreate,
	TrackPublic,
	TrackRead,
	UserCreate,
	UserPublic,
	UserRead,
	UserUpdate,
	VoiceModelRead,
)
from gbedu_core.security import (
	create_access_token,
	create_refresh_token,
	decode_token,
	generate_api_key,
	hash_password,
	oauth2_scheme,
	verify_access_token,
	verify_api_key,
	verify_password,
	verify_refresh_token,
	verify_token,
)
from gbedu_core.telemetry import (
	configure_telemetry,
	get_meter,
	get_tracer,
	increment_error_count,
	increment_generation_count,
	record_generation_duration,
	traced,
)

__all__ = [
	# uuid7
	"uuid7str",
	# config
	"Settings",
	"get_settings",
	"DatabaseSettings",
	"RedisSettings",
	"StorageSettings",
	"StripeSettings",
	"PaystackSettings",
	"JWTSettings",
	"MLSettings",
	"CelerySettings",
	"ObservabilitySettings",
	"EmailSettings",
	# errors — codes
	"EC_VALIDATION",
	"EC_AUTHENTICATION",
	"EC_AUTHORIZATION",
	"EC_NOT_FOUND",
	"EC_CONFLICT",
	"EC_RATE_LIMIT",
	"EC_PAYMENT",
	"EC_PAYMENT_DECLINED",
	"EC_PAYMENT_WEBHOOK",
	"EC_STORAGE",
	"EC_STORAGE_UPLOAD",
	"EC_STORAGE_DELETE",
	"EC_ML_SERVICE",
	"EC_ML_TIMEOUT",
	"EC_GENERATION",
	"EC_GENERATION_QUOTA",
	"EC_WORKER",
	"EC_WORKER_TIMEOUT",
	"EC_DATABASE",
	"EC_DATABASE_CONNECTION",
	"EC_DATABASE_INTEGRITY",
	"EC_TOKEN_EXPIRED",
	"EC_TOKEN_INVALID",
	"EC_INVALID_CREDENTIALS",
	# errors — classes
	"GbeduError",
	"ValidationError",
	"AuthenticationError",
	"TokenExpiredError",
	"TokenInvalidError",
	"InvalidCredentialsError",
	"AuthorizationError",
	"NotFoundError",
	"ConflictError",
	"RateLimitError",
	"PaymentError",
	"PaymentDeclinedError",
	"PaymentWebhookError",
	"StorageError",
	"StorageUploadError",
	"StorageDeleteError",
	"MLServiceError",
	"MLServiceTimeoutError",
	"GenerationError",
	"GenerationQuotaError",
	"WorkerError",
	"WorkerTimeoutError",
	"DatabaseError",
	"DatabaseConnectionError",
	"DatabaseIntegrityError",
	# logging
	"configure_logging",
	"get_logger",
	"LogContext",
	# db
	"Base",
	"TimestampMixin",
	"SoftDeleteMixin",
	"get_engine",
	"make_session_factory",
	"init_db",
	"get_db",
	"ping_database",
	# security
	"hash_password",
	"verify_password",
	"create_access_token",
	"create_refresh_token",
	"verify_token",
	"verify_access_token",
	"verify_refresh_token",
	"decode_token",
	"generate_api_key",
	"verify_api_key",
	"oauth2_scheme",
	# telemetry
	"configure_telemetry",
	"get_tracer",
	"get_meter",
	"traced",
	"record_generation_duration",
	"increment_generation_count",
	"increment_error_count",
	# health
	"HealthState",
	"HealthStatus",
	"AggregateHealth",
	"check_database",
	"check_redis",
	"check_ml_service",
	"check_storage",
	# models
	"User",
	"SubscriptionTier",
	"SubscriptionStatus",
	"Track",
	"SubGenre",
	"Language",
	"TrackStatus",
	"GenerationJob",
	"JobStatus",
	"Subscription",
	"Payment",
	"Invoice",
	"PaymentProvider",
	"PaymentStatus",
	"InvoiceStatus",
	"VoiceModel",
	"VoiceModelStatus",
	"VoiceArchetype",
	"BeatListing",
	"BeatPurchase",
	"ListingStatus",
	# schemas
	"UserCreate",
	"UserRead",
	"UserUpdate",
	"UserPublic",
	"TrackCreate",
	"TrackRead",
	"TrackPublic",
	"GenerationRequest",
	"GenerationResponse",
	"JobRead",
	"JobStatusUpdate",
	"SubscriptionRead",
	"PaymentRead",
	"InvoiceRead",
	"VoiceModelRead",
	"BeatListingRead",
	"BeatPurchaseRead",
	"TokenResponse",
	"RefreshRequest",
]
