---
apiVersion: v1
kind: Service
metadata:
  name: gbedu-web
  namespace: gbedu-prod
  labels:
    app: gbedu-web
    app.kubernetes.io/name: gbedu-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: gbedu
spec:
  type: ClusterIP
  selector:
    app: gbedu-web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
