import Link from "next/link"

export const metadata = {
	title: "Terms of Service — Gbẹdu",
	description: "Read the Gbẹdu Terms of Service.",
}

export default function TermsPage() {
	return (
		<div className="min-h-dvh px-4 py-16 relative">
			<div
				className="absolute inset-0"
				style={{ background: "radial-gradient(ellipse at 50% 0%, rgba(212,175,55,0.05) 0%, transparent 60%)" }}
			/>

			<div className="relative max-w-2xl mx-auto space-y-8">
				<nav className="text-sm text-zinc-500">
					<Link href="/" className="hover:text-afro-gold transition-colors">
						Gbẹdu
					</Link>{" "}
					/ Terms of Service
				</nav>

				<div>
					<p className="text-afro-gold text-sm font-medium mb-1">Legal</p>
					<h1 className="font-display text-3xl font-bold text-zinc-100">Terms of Service</h1>
					<p className="text-zinc-500 text-sm mt-1">
						Effective: 1 January 2025 &mdash; Last updated: 15 June 2026
					</p>
				</div>

				<div className="space-y-6 text-zinc-400 text-sm leading-relaxed">
					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">1. Acceptance</h2>
						<p>
							By accessing or using Gbẹdu you agree to be bound by these Terms and our{" "}
							<Link href="/privacy" className="text-afro-gold hover:underline">
								Privacy Policy
							</Link>
							. If you do not agree, do not use the platform.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">2. Description of service</h2>
						<p>
							Gbẹdu is an AI-powered Afrobeats music generation platform. We provide tools for creating,
							editing, licensing, and distributing music using generative AI models.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">3. User accounts</h2>
						<p>
							You must be at least 16 years old to create an account. You are responsible for maintaining
							the confidentiality of your credentials and for all activity under your account. Notify us
							immediately at{" "}
							<a href="mailto:security@gbedu.io" className="text-afro-gold hover:underline">
								security@gbedu.io
							</a>{" "}
							if you suspect unauthorised access.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">
							4. Generated content and intellectual property
						</h2>
						<p>
							Subject to your subscription plan, you own the commercial rights to music you generate
							using Gbẹdu. You grant us a limited, non-exclusive licence to host, transcode, and deliver
							your content. You warrant that any materials you upload (voice samples, reference tracks,
							stems) do not infringe third-party intellectual property rights.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">5. Prohibited uses</h2>
						<p>You may not use Gbẹdu to:</p>
						<ul className="list-disc list-inside space-y-1 ml-2">
							<li>Generate content that infringes third-party intellectual property;</li>
							<li>Produce defamatory, obscene, or unlawful content;</li>
							<li>Reverse-engineer, extract, or redistribute model weights;</li>
							<li>Circumvent access controls, rate limits, or subscription restrictions;</li>
							<li>Train competing AI models using content generated by Gbẹdu.</li>
						</ul>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">6. Marketplace</h2>
						<p>
							Sellers warrant they hold the necessary rights to all listed content. Gbẹdu collects a
							platform fee on each transaction. Exclusive licence sales are final and non-refundable once
							the beat is delivered.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">7. Subscriptions and payments</h2>
						<p>
							Subscriptions renew automatically at the end of each billing cycle unless cancelled before
							the renewal date. Monthly subscriptions are non-refundable. Annual subscriptions may
							receive a pro-rated refund for unused months at our discretion.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">8. Termination</h2>
						<p>
							We may suspend or terminate accounts for material breach of these Terms. On termination,
							your licence to use the platform ends immediately. Tracks already downloaded to your device
							remain yours under the applicable licence.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">9. Disclaimers</h2>
						<p>
							Gbẹdu is provided &ldquo;as is&rdquo;. We make no warranty that the service will be
							uninterrupted, error-free, or that AI-generated output will meet your expectations.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">10. Limitation of liability</h2>
						<p>
							To the fullest extent permitted by applicable law, Gbẹdu&apos;s total liability for any
							claim arising out of or related to these Terms is limited to the amounts you paid us in
							the twelve months preceding the claim.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">11. Governing law</h2>
						<p>
							These Terms are governed by the laws of England and Wales. Disputes shall be submitted to
							the exclusive jurisdiction of the courts of London, UK, except where mandatory local law
							requires otherwise.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">12. Changes to these Terms</h2>
						<p>
							We may update these Terms. Material changes will be communicated by email or in-app notice
							at least 14 days before they take effect. Continued use after that date constitutes
							acceptance.
						</p>
					</section>

					<section className="space-y-2">
						<h2 className="text-zinc-100 font-semibold text-base">13. Contact</h2>
						<p>
							Questions about these Terms?{" "}
							<a href="mailto:legal@gbedu.io" className="text-afro-gold hover:underline">
								legal@gbedu.io
							</a>{" "}
							or use our{" "}
							<Link href="/contact" className="text-afro-gold hover:underline">
								contact form
							</Link>
							.
						</p>
					</section>
				</div>

				<div className="border-t border-white/[0.06] pt-6 flex gap-4 text-xs text-zinc-500">
					<Link href="/privacy" className="hover:text-afro-gold transition-colors">
						Privacy Policy
					</Link>
					<Link href="/contact" className="hover:text-afro-gold transition-colors">
						Contact
					</Link>
				</div>
			</div>
		</div>
	)
}
